# Generated by Django 5.1.1 on 2024-09-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
