# Generated by Django 5.1.1 on 2024-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_bot', '0002_trip_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MUSEUM_NAME', models.CharField(max_length=200, null=True)),
                ('PINCODE', models.IntegerField(default=132001, null=True)),
                ('ADULTPRICE', models.IntegerField(null=True)),
                ('CHILDPRICE', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'museum_list',
            },
        ),
    ]
