# Generated by Django 5.1.1 on 2024-09-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_bot', '0003_museum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='museum',
            table=None,
        ),
    ]
